controller_list:
  - name: zlab_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - arm1_j1
      - arm1_j2
      - arm1_j3
      - arm1_j4
      - arm1_j5
      - arm1_j6