controller_list:
  - name: fake_fr5v6_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - frrobot_j1
      - frrobot_j2
      - frrobot_j3
      - frrobot_j4
      - frrobot_j5
      - frrobot_j6
  - name: fake_tool_controller
    type: $(arg fake_execution_type)
    joints:
      []
initial:  # Define initial robot poses per group
  - group: fr5v6_arm
    pose: zero