fr5v6_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - frrobot_j1
    - frrobot_j2
    - frrobot_j3
    - frrobot_j4
    - frrobot_j5
    - frrobot_j6
  gains:
    frrobot_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    frrobot_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    frrobot_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    frrobot_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    frrobot_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    frrobot_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1