arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - fr5v6_j1
    - fr5v6_j2
    - fr5v6_j3
    - fr5v6_j4
    - fr5v6_j5
    - fr5v6_j6
  gains:
    fr5v6_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fr5v6_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fr5v6_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fr5v6_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fr5v6_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    fr5v6_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1