controller_list:
  - name: frrobot/fr5v6_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - frrobot_j1
      - frrobot_j2
      - frrobot_j3
      - frrobot_j4
      - frrobot_j5
      - frrobot_j6