# Hardware interface settings
hardware_interface:
  joints:
    - arm1_j1
    - arm1_j2
    - arm1_j3
    - arm1_j4
    - arm1_j5
    - arm1_j6

# Control loop settings
loop_hz: 60.0
cycle_time_error_threshold: 0.01

# Motion parameters
acc: 0.0
vel: 0.0
cmd_t: 0.002
filter_t: 0.002
gain: 0.0

# Joint state controller
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Trajectory controller
arm1_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm1_j1
    - arm1_j2
    - arm1_j3
    - arm1_j4
    - arm1_j5
    - arm1_j6
  constraints:
    goal_time: 3.0
    stopped_velocity_tolerance: 0.0
    arm1_j1:
      trajectory: 0.60
      goal: 0.15
    arm1_j2:
      trajectory: 0.60
      goal: 0.15
    arm1_j3:
      trajectory: 0.60
      goal: 0.15
    arm1_j4:
      trajectory: 0.60
      goal: 0.15
    arm1_j5:
      trajectory: 0.60
      goal: 0.15
    arm1_j6:
      trajectory: 0.60
      goal: 0.15

