arm1_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm1_j1
    - arm1_j2
    - arm1_j3
    - arm1_j4
    - arm1_j5
    - arm1_j6
  constraints:
    goal_time: 3.0
    stopped_velocity_tolerance: 0.0
    arm1_j1:
      trajectory: 0.05
      goal: 0.01
    arm1_j2:
      trajectory: 0.05
      goal: 0.01
    arm1_j3:
      trajectory: 0.05
      goal: 0.01
    arm1_j4:
      trajectory: 0.05
      goal: 0.01
    arm1_j5:
      trajectory: 0.05
      goal: 0.01
    arm1_j6:
      trajectory: 0.05
      goal: 0.01
  gains:
    arm1_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm1_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm2_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - arm2_j1
    - arm2_j2
    - arm2_j3
    - arm2_j4
    - arm2_j5
    - arm2_j6
  constraints:
    goal_time: 3.0
    stopped_velocity_tolerance: 0.0
    arm2_j1:
      trajectory: 0.05
      goal: 0.01
    arm2_j2:
      trajectory: 0.05
      goal: 0.01
    arm2_j3:
      trajectory: 0.05
      goal: 0.01
    arm2_j4:
      trajectory: 0.05
      goal: 0.01
    arm2_j5:
      trajectory: 0.05
      goal: 0.01
    arm2_j6:
      trajectory: 0.05
      goal: 0.01
  gains:
    arm2_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm2_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm2_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm2_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm2_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm2_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

position_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - diana7_joint_1
    - diana7_joint_2
    - diana7_joint_3
    - diana7_joint_4
    - diana7_joint_5
    - diana7_joint_6
    - diana7_joint_7
  constraints:
    goal_time: 3.0
    stopped_velocity_tolerance: 0.0
    diana7_joint_1:
      trajectory: 0.05
      goal: 0.01
    diana7_joint_2:
      trajectory: 0.05
      goal: 0.01
    diana7_joint_3:
      trajectory: 0.05
      goal: 0.01
    diana7_joint_4:
      trajectory: 0.05
      goal: 0.01
    diana7_joint_5:
      trajectory: 0.05
      goal: 0.01
    diana7_joint_6:
      trajectory: 0.05
      goal: 0.01
    diana7_joint_7:
      trajectory: 0.05
      goal: 0.01
