controller_list:
  - name: arm1/arm1_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - arm1_joint_1
      - arm1_joint_2
      - arm1_joint_3
      - arm1_joint_4
      - arm1_joint_5
      - arm1_joint_6
  - name: arm2/arm2_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - arm2_joint_1
      - arm2_joint_2
      - arm2_joint_3
      - arm2_joint_4
      - arm2_joint_5
      - arm2_joint_6
  - name: diana7/position_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - diana7_joint_1
      - diana7_joint_2
      - diana7_joint_3
      - diana7_joint_4
      - diana7_joint_5
      - diana7_joint_6
      - diana7_joint_7
