robot1_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot1_j1
    - robot1_j2
    - robot1_j3
    - robot1_j4
    - robot1_j5
    - robot1_j6
  gains:
    robot1_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot1_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
robot2_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot2_j1
    - robot2_j2
    - robot2_j3
    - robot2_j4
    - robot2_j5
    - robot2_j6
  gains:
    robot2_j1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot2_j2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot2_j3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot2_j4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot2_j5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robot2_j6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1