tag_family: tag36h11

# 相机坐标系
camera_frame: camera_color_optical_frame

# 是否发布 TF
publish_tf: true

# ===== 独立 AprilTag（推荐）=====
standalone_tags:
  - id: 109
    size: 0.032
    frame_name: tag_dianna

  - id: 208
    size: 0.032
    frame_name: tag_red

  - id: 104
    size: 0.032
    frame_name: tag_green
