controller_list:
  - name: fake_fr5_controller
    type: $(arg fake_execution_type)
    joints:
      - $(arg arm_id)_joint_1
      - $(arg arm_id)_joint_2
      - $(arg arm_id)_joint_3
      - $(arg arm_id)_joint_4
      - $(arg arm_id)_joint_5
      - $(arg arm_id)_joint_6
initial:  # Define initial robot poses per group
  - group: fr5
    pose: up

