controller_list:
  - name: $(arg arm_id)/$(arg arm_id)_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - $(arg arm_id)_joint_1
      - $(arg arm_id)_joint_2
      - $(arg arm_id)_joint_3
      - $(arg arm_id)_joint_4
      - $(arg arm_id)_joint_5
      - $(arg arm_id)_joint_6

