# Hardware Interface Settings
hardware_interface:
  joints:
    - $(arg prefix)j1
    - $(arg prefix)j2
    - $(arg prefix)j3
    - $(arg prefix)j4
    - $(arg prefix)j5
    - $(arg prefix)j6
    - $(arg prefix)j7
  ip_address: "192.168.31.200"
  loop_hz: 100.0

# Controller Settings
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

position_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - $(arg prefix)j1
    - $(arg prefix)j2
    - $(arg prefix)j3
    - $(arg prefix)j4
    - $(arg prefix)j5
    - $(arg prefix)j6
    - $(arg prefix)j7
  constraints:
    goal_time: 2.0
    stopped_velocity_tolerance: 0.1
    $(arg prefix)j1: {trajectory: 1.0, goal: 0.5}
    $(arg prefix)j2: {trajectory: 1.0, goal: 0.5}
    $(arg prefix)j3: {trajectory: 1.0, goal: 0.5}
    $(arg prefix)j4: {trajectory: 1.0, goal: 0.5}
    $(arg prefix)j5: {trajectory: 1.0, goal: 0.5}
    $(arg prefix)j6: {trajectory: 1.0, goal: 0.5}
    $(arg prefix)j7: {trajectory: 1.0, goal: 0.5}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
