# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 101, size: 0.03, name: 'tag_101'},
    {id: 102, size: 0.03, name: 'tag_102'},
    {id: 103, size: 0.03, name: 'tag_103'},
    {id: 104, size: 0.03, name: 'tag_104'},
    {id: 105, size: 0.03, name: 'tag_105'},
    {id: 201, size: 0.032, name: 'tag_201'},
    {id: 202, size: 0.032, name: 'tag_202'},
    {id: 203, size: 0.032, name: 'tag_203'}
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
  ]