robot1_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
        - robot1_j1
        - robot1_j2
        - robot1_j3
        - robot1_j4
        - robot1_j5
        - robot1_j6
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        robot1_j1: {trajectory: 0.1, goal: 0.1}
        robot1_j2: {trajectory: 0.1, goal: 0.1}
        robot1_j3: {trajectory: 0.1, goal: 0.1}
        robot1_j4: {trajectory: 0.1, goal: 0.1}
        robot1_j5: {trajectory: 0.1, goal: 0.1}
        robot1_j6: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

robot2_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
        - robot2_j1
        - robot2_j2
        - robot2_j3
        - robot2_j4
        - robot2_j5
        - robot2_j6
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        robot2_j1: {trajectory: 0.1, goal: 0.1}
        robot2_j2: {trajectory: 0.1, goal: 0.1}
        robot2_j3: {trajectory: 0.1, goal: 0.1}
        robot2_j4: {trajectory: 0.1, goal: 0.1}
        robot2_j5: {trajectory: 0.1, goal: 0.1}
        robot2_j6: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

