controller_list:
  - name: fake_robot1_controller
    type: $(arg fake_execution_type)
    joints:
      - robot1_j1
      - robot1_j2
      - robot1_j3
      - robot1_j4
      - robot1_j5
      - robot1_j6
  - name: fake_robot2_controller
    type: $(arg fake_execution_type)
    joints:
      - robot2_j1
      - robot2_j2
      - robot2_j3
      - robot2_j4
      - robot2_j5
      - robot2_j6
  - name: fake_dual_robots_controller
    type: $(arg fake_execution_type)
    joints:
      - robot1_j1
      - robot1_j2
      - robot1_j3
      - robot1_j4
      - robot1_j5
      - robot1_j6
      - robot2_j1
      - robot2_j2
      - robot2_j3
      - robot2_j4
      - robot2_j5
      - robot2_j6
initial:  # Define initial robot poses per group
  - group: robot1
    pose: zero
  - group: robot2
    pose: zero
  - group: dual_robots
    pose: ready