controller_list:
  - name: fake_arm1_controller
    type: $(arg fake_execution_type)
    joints:
      - arm1_j1
      - arm1_j2
      - arm1_j3
      - arm1_j4
      - arm1_j5
      - arm1_j6
  - name: fake_arm2_controller
    type: $(arg fake_execution_type)
    joints:
      - arm2_j1
      - arm2_j2
      - arm2_j3
      - arm2_j4
      - arm2_j5
      - arm2_j6
initial:  # Define initial robot poses per group
  - group: arm1
    pose: zero
  - group: arm2
    pose: zero
  - group: dual_arms
    pose: zero

