controller_list:
  - name: fake_diana_arm_controller
    type: interpolate
    joints:
      - diana7_j1
      - diana7_j2
      - diana7_j3
      - diana7_j4
      - diana7_j5
      - diana7_j6
      - diana7_j7
initial:  # Define initial robot poses.
  - group: diana_arm
    pose: home
